def invalid_url_error(logs):
    logs.append("URL is not valid")
